name: Deploy Node.js Application

on:
  push:
    branches:
      - main  # Adjust this if you want to deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjust Node.js version if needed

    - name: Setup SSH with PEM Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/test-pankaj.pem
        chmod 600 ~/.ssh/test-pankaj.pem
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    - name: Verify SSH Connection
      run: |
        ssh -i ~/.ssh/test-pankaj.pem -vvv ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'SSH Connection Successful'"

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/test-pankaj.pem -vvv ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          set -x  # Enable command tracing
          cd /home/ubuntu/frontend || { echo "Directory change failed"; exit 1; }

          # Fetch the latest code
          git pull origin main || { echo "Git pull failed"; exit 1; }

          # Clean npm environment
          rm -rf node_modules package-lock.json

          # Install dependencies
          npm install || { echo "npm install failed"; exit 1; }

          # Build the application
          npm run build || { echo "npm build failed"; exit 1; }

          # Start the application with PM2
          pm2 start npm --name "react-app" -- start || { echo "PM2 start failed"; exit 1; }
        EOF
